export const HTML_ROUTES = new Set([
  "/",
  "/about/",
  "/authors/",
  "/bar-top-epoxy-calculator/",
  "/contact/",
  "/countertop-epoxy-calculator/",
  "/cube-resin-calculator/",
  "/cylinder-resin-calculator/",
  "/de/",
  "/de/epoxidboden-rechner/",
  "/de/epoxidharz-kosten-pro-m2/",
  "/de/epoxidharz-verbrauch-pro-m2/",
  "/deep-pour-epoxy-calculator/",
  "/deep-pour-vs-table-top-epoxy/",
  "/epoxy-bar-top-cost/",
  "/epoxy-calculator-metric/",
  "/epoxy-calculator/",
  "/epoxy-circle-calculator/",
  "/epoxy-cost-calculator/",
  "/epoxy-cost-per-square-foot/",
  "/epoxy-countertop-cost/",
  "/epoxy-coverage-calculator/",
  "/epoxy-coverage-chart/",
  "/epoxy-flood-coat-calculator/",
  "/epoxy-floor-coverage-calculator/",
  "/epoxy-kit-size-guide/",
  "/epoxy-mix-ratio-by-volume-vs-weight/",
  "/epoxy-mixing-ratio-guide/",
  "/epoxy-pour-calculator/",
  "/epoxy-pour-depth-guide/",
  "/epoxy-rectangle-calculator/",
  "/epoxy-seal-coat-calculator/",
  "/epoxy-unit-converter/",
  "/epoxy-waste-factor-guide/",
  "/es/",
  "/es/calculadora-suelo-epoxi/",
  "/es/consumo-resina-epoxi-por-m2/",
  "/es/precio-suelo-epoxi-m2/",
  "/faq/",
  "/fr/",
  "/fr/calculateur-sol-epoxy/",
  "/fr/prix-resine-epoxy-m2/",
  "/fr/quantite-resine-epoxy-par-m2/",
  "/garage-floor-epoxy-calculator/",
  "/how-much-does-a-gallon-of-epoxy-cover/",
  "/how-much-epoxy-do-i-need-for-a-river-table/",
  "/how-much-epoxy-do-i-need/",
  "/how-much-epoxy-per-square-foot/",
  "/how-to-calculate-epoxy-pour/",
  "/how-to-measure-a-river-table-for-epoxy/",
  "/how-to-prevent-epoxy-leaks/",
  "/it/",
  "/it/calcolatore-pavimento-epossidico/",
  "/it/consumo-resina-epossidica-m2/",
  "/it/prezzo-pavimento-resina-epossidica-m2/",
  "/maximum-epoxy-pour-depth/",
  "/methodology/",
  "/privacy/",
  "/pt-br/",
  "/pt-br/calculadora-piso-epoxi/",
  "/pt-br/calculadora-volume-resina-epoxi/",
  "/pt-br/consumo-resina-epoxi-por-m2/",
  "/pt-br/preco-piso-epoxi-m2/",
  "/pt-br/quanta-resina-epoxi-preciso/",
  "/resin-art-pricing-calculator/",
  "/resin-coaster-calculator/",
  "/resin-dice-calculator/",
  "/resin-jewelry-calculator/",
  "/resin-mold-calculator/",
  "/resin-tray-calculator/",
  "/river-table-epoxy-calculator/",
  "/river-table-epoxy-cost/",
  "/round-epoxy-table-calculator/",
  "/seal-coat-vs-flood-coat/",
  "/sphere-resin-calculator/",
  "/table-top-epoxy-calculator/",
  "/terms/",
  "/two-car-garage-epoxy-calculator/",
  "/void-fill-epoxy-calculator/"
]);

export const REDIRECTS = new Map([
  ["/de/epoxidharz-rechner/", "/de/"],
  ["/de/epoxidharz-volumen-rechner/", "/de/"],
  ["/de/garagenboden-epoxidharz-kosten/", "/de/epoxidharz-kosten-pro-m2/"],
  ["/de/wie-viel-epoxidharz-brauche-ich/", "/de/"],
  ["/de/wie-viel-epoxidharz-fuer-garage/", "/de/epoxidboden-rechner/"],
  ["/epoxy-amount-calculator/", "/epoxy-calculator/"],
  ["/epoxy-garage-floor-cost/", "/garage-floor-epoxy-calculator/"],
  ["/epoxy-garage-floor-cost-calculator/", "/garage-floor-epoxy-calculator/"],
  ["/epoxy-square-foot-calculator/", "/epoxy-coverage-calculator/"],
  ["/epoxy-volume-calculator/", "/epoxy-calculator/"],
  ["/es/calculadora-resina-epoxi/", "/es/"],
  ["/es/calculadora-volumen-resina-epoxi/", "/es/"],
  ["/es/cuanta-resina-epoxi-necesito/", "/es/"],
  ["/es/cuanta-resina-epoxi-para-garaje/", "/es/calculadora-suelo-epoxi/"],
  ["/es/precio-epoxi-garaje/", "/es/precio-suelo-epoxi-m2/"],
  ["/fr/calculateur-resine-epoxy/", "/fr/"],
  ["/fr/calculateur-volume-resine-epoxy/", "/fr/"],
  ["/fr/combien-de-resine-epoxy-faut-il/", "/fr/"],
  ["/fr/combien-de-resine-epoxy-pour-un-garage/", "/fr/calculateur-sol-epoxy/"],
  ["/fr/prix-sol-garage-epoxy/", "/fr/prix-resine-epoxy-m2/"],
  ["/it/calcolatore-resina-epossidica/", "/it/"],
  ["/it/calcolatore-volume-resina-epossidica/", "/it/"],
  ["/it/costo-pavimento-epossidico-garage/", "/it/prezzo-pavimento-resina-epossidica-m2/"],
  ["/it/quanta-resina-epossidica-per-garage/", "/it/calcolatore-pavimento-epossidico/"],
  ["/it/quanta-resina-epossidica-serve/", "/it/"],
  ["/pt-br/calculadora-resina-epoxi/", "/pt-br/"],
  ["/pt-br/piso-epoxi-garagem-preco/", "/pt-br/preco-piso-epoxi-m2/"],
  ["/pt-br/quanta-resina-epoxi-para-garagem/", "/pt-br/calculadora-piso-epoxi/"],
  ["/resin-calculator/", "/epoxy-calculator/"]
]);
